// Holds values for actions

export const IS_FETCHING_AUTH = 'IS_FETCHING_AUTH'

export const REMOVE_IS_FETCHING_AUTH = 'REMOVE_IS_FETCHING_AUTH'

export const LOGIN_FAILURE = "LOGIN_FAILURE"

export const LOGIN_SUCCESS = "LOGIN_SUCCESS"

export const GET_PROFILE = 'GET_PROFILE'

export const REMOVE_PROFILE = 'REMOVE_PROFILE'

export const SET_DB_PROFILE = 'SET_DB_PROFILE'

export const REMOVE_DB_PROFILE = 'REMOVE_DB_PROFILE'

export const FETCH_DB_POSTS_SUCCESS = 'FETCH_DB_POSTS_SUCCESS'

export const REMOVE_DB_POSTS = 'REMOVE_DB_POSTS'

export const FETCH_DB_POST_COMMENTS_SUCCESS = 'FETCH_DB_POST_COMMENTS_SUCCESS'

export const DB_POST_COMMENTS_FAILURE = 'DB_POST_COMMENTS_FAILURE'

export const SEARCH_POSTS_SUCCESS = "SEARCH_POSTS_SUCCESS"

export const SEARCH_POSTS_FAILURE = "SEARCH_POSTS_FAILURE"

export const FETCH_OTHER_USER_DB_POSTS_SUCCESS = 'FETCH_OTHER_USER_DB_POSTS_SUCCESS'

export const REMOVE_OTHER_USER_DB_POSTS = 'REMOVE_OTHER_USER_DB_POSTS'

export const SET_OTHER_USER_DB_PROFILE = 'SET_OTHER_USER_DB_PROFILE'

export const REMOVE_OTHER_USER_DB_PROFILE = 'REMOVE_OTHER_USER_DB_PROFILE'

export const SET_USER_MESSAGES = 'SET_USER_MESSAGES'

export const REMOVE_USER_MESSAGES = 'REMOVE_USER_MESSAGES'
